### ISSUE TITLE
contract statement for basis_to_python

### ISSUE THREAD

**Issue by madscatt** [madscatt/sasmol#18]
Define and review scope of method to be used throughout sassie 2.

**Comment by madscatt** [comment]
The goal is to complete a method/library to allow user (and programmatic) definitions to handle various sub-selections of sasmol objects in a more human readable way.  Remove the requirement for basis strings that use eval() directly, thus ridding [] and == and " " in most cases.  Will add support for all sasmol object defined fields, but we will probably only document the standard PDB fields for user input.  

The tokenization code will be updated and in some cases fixed with side-by-side unit tests for functionality.

Note that in addition to the allowed options in the initial markdown document, X, Y & Z coordinates.

At this point, only 'charge' will require quotation marks as it is defined as a two-character string.  We may be able to get around this if it remains the only outlier.

**Comment by skrueger111** [comment]
The options in the initial markdown document were taken from the Build documents (Case 3).  X, Y and Z coordinates were not included since the document was created with SasCalc and TAMC in mind. Also excluded were altloc and icode.  If these are not sasmol object defined fields, then they don't need to be included.
